---
title: "Customer Intelligence"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r global, include=FALSE}
 

# if(!require(flexdashboard)) install.packages("flexdashboard",repos = "http://cran.us.r-project.org")
# if(!require(geojsonio)) install.packages("geojsonio",repos = "http://cran.us.r-project.org")
library(sf)
library(rgdal)
library(dplyr)
library(shiny)
library(rmapshaper)
library(purrr)
library(tidycensus)
library(tidyr)
library(mapview)
library(sp)
library(geojsonio)
#install.packages("flexdashboard")
library(flexdashboard)
library(readr)
library(leaflet)
library(DT)
library(tidyverse)
library(lubridate)
library(plotly)
library(sf)
 setwd("C:/Users/blake/OneDrive/Stryker Project/Country Leaflet Information Dashboard/Building Leaflet Final Interactive Map/Leaflet Map App")


# Load data
county <- readOGR(dsn=".", layer = "cb_2018_us_county_500k")
# # # # convert the GEOID to a character (BECAUSE TIDY CENSUS IS CHARACTER FOR SF FILE)
county@data$GEOID <-as.character(county@data$GEOID)

df.polygon <- county

# # # # # # # # County shape dataframe subset this!!!
df.polygon2  <- df.polygon# moving variable

# # # # # # # # Load dataframe
census <- read.csv("census.csv");census <- census[-c(1)];census <- census[c(1,2,3,7,10,14)];census$GEOID <-  as.character(census$GEOID)
# #  #  # 

census$GEOID <-ifelse(census$state == " Alabama",paste("0",census$GEOID,sep =""),census$GEOID)
census$GEOID <-ifelse(census$state == " Arkansas",paste("0",census$GEOID,sep =""),census$GEOID)
census$GEOID <-ifelse(census$state == " California",paste("0",census$GEOID,sep =""),census$GEOID)
census$GEOID <-ifelse(census$state == " Arizona",paste("0",census$GEOID,sep =""),census$GEOID)
census$GEOID <-ifelse(census$state == " Colorado",paste("0",census$GEOID,sep =""),census$GEOID)
census$GEOID <-ifelse(census$state == " Connecticut",paste("0",census$GEOID,sep =""),census$GEOID)
census$GEOID <-ifelse(census$state == " Alaska",paste("0",census$GEOID,sep =""),census$GEOID)

df.polygon5 <- rmapshaper::ms_simplify(df.polygon2, keep = 0.05, keep_shapes = TRUE)

df.polygon5@data <- left_join(df.polygon5@data, census,by = c("GEOID"),all.x = TRUE)

options(tigris_use_cache = TRUE)
lifecycle::last_warnings()
# 
# # # # get state information
#   stateid <- read.csv("statesid.csv");us <- stateid$state_id
# # # # 
# # # # # Get information for every county and then go back and fill in the rest
#    totcountchar <- NULL;
#    for(i in 1:length(unique(us))){
#      totalcountypop <-NULL;
#      tryCatch({ 
#    totalcountypop <- get_estimates(geography = "county",
#                                    product = "characteristics",
#                                    breakdown = c("SEX", "AGEGROUP", "HISP","RACE"),
#                              breakdown_labels = TRUE,
#                                    state = us[i])
#      }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
#    totcountchar <- rbind(totcountchar,totalcountypop)
#   }
# # 
# # # # Saving county characteristics
# compare <- filter(totcountchar, str_detect(AGEGROUP, "^Age"),
#                         HISP != "Both Hispanic Origins",
#                       SEX != "Both sexes") %>%
#         mutate(value = ifelse(SEX == "Male", -value, value)) 

compare <- read.csv("compare.csv");compare <- compare[-c(1)]
compare$GEOID <-ifelse(grepl("Alabama", compare$NAME, fixed = TRUE),paste("0",compare$GEOID,sep =""),compare$GEOID)
 compare$GEOID <-ifelse(grepl("Arkansas", compare$NAME, fixed = TRUE),paste("0",compare$GEOID,sep =""),compare$GEOID)
 compare$GEOID <-ifelse(grepl("California", compare$NAME, fixed = TRUE),paste("0",compare$GEOID,sep =""),compare$GEOID)
 compare$GEOID <-ifelse(grepl("Arizona", compare$NAME, fixed = TRUE),paste("0",compare$GEOID,sep =""),compare$GEOID)
 compare$GEOID <-ifelse(grepl("Colorado", compare$NAME, fixed = TRUE),paste("0",compare$GEOID,sep =""),compare$GEOID)
 compare$GEOID <-ifelse(grepl("Connecticut", compare$NAME, fixed = TRUE),paste("0",compare$GEOID,sep =""),compare$GEOID)
 compare$GEOID <-ifelse(grepl("Alaska", compare$NAME, fixed = TRUE),paste("0",compare$GEOID,sep =""),compare$GEOID)
 
 # load zip information
 zcta <- readOGR(dsn = ".",layer = "cb_2018_us_zcta510_500k")
 
# # # # # Zip code level information
    totalpop2011 <-  "B01003_001" # population variable
# #  # 
# # # # # grabbing census information
   ZIPpopulation <- get_acs(geography = "zcta",
                             variables = totalpop2011,
                             year = 2011, survey = "acs5",
                             output = "wide", geometry = TRUE,
                             keep_geo_vars=TRUE)
 
# # # # # convert county to zip
   countytozip <- read.csv("uszips.csv");colnames(countytozip)[1] <- "GEOID";countytozip$GEOID <- as.character(countytozip$GEOID);countytozip$COUNTY <- as.character(countytozip$COUNTY)
#  # # 
   zipmap <- merge(ZIPpopulation,countytozip,by=c("GEOID"),all.x=TRUE)
   zipmap2 <- zipmap[!is.na(zipmap$county_name),]
   colnames(zipmap2)[1] <- "GEOID10"

# # # DONT NEED THIS JUST YET
   zcta <- readOGR(dsn = ".",layer = "cb_2018_us_zcta510_500k")

   zcta@data <- left_join(zcta@data, zipmap2,by = c("GEOID10"),all.x = TRUE)
###################################################################################
#    # # # # # census covid for time slider
#  #Load the dataframe from the folder
#  countyz <- readOGR(dsn=".", layer = "cb_2018_us_county_500k")
# # # convert the GEOID to a character (BECAUSE TIDY CENSUS IS CHARACTER FOR SF FILE)
#  countyz@data$GEOID <-as.character(countyz@data$GEOID)
# # # # 
# # # # # final shape file 
#    df.polygonz <- countyz
# # # # # # 
# # # #  County shape dataframe subset this!!!
#    df.polygon2z  <- df.polygonz# moving variable
# # # # # 
# # # # # # Make map for slider
#    df.polygon4z <- rmapshaper::ms_simplify(df.polygon2z, keep = 0.05, keep_shapes = TRUE)
# # # # # 
# # #  # for dropdown rendering
# #  ############ df.polygon5 <- rmapshaper::ms_simplify(df.polygon2, keep = 0.05, keep_shapes = TRUE)
# # #  
# # # # # # census covid for time slider
#  censuscovid <- read.csv("censuscovid.csv");censuscovid <- censuscovid[-c(1)]; censuscovid$GEOID <- as.character(censuscovid$GEOID); 
# # # 
# # #  # # not needed anymore
#   censuscovid$GEOID <-ifelse(censuscovid$state == " Alabama",paste("0",censuscovid$GEOID,sep =""),censuscovid$GEOID)
#   censuscovid$GEOID <-ifelse(censuscovid$state == " Arkansas",paste("0",censuscovid$GEOID,sep =""),censuscovid$GEOID)
#   censuscovid$GEOID <-ifelse(censuscovid$state == " California",paste("0",censuscovid$GEOID,sep =""),censuscovid$GEOID)
#   censuscovid$GEOID <-ifelse(censuscovid$state == " Arizona",paste("0",censuscovid$GEOID,sep =""),censuscovid$GEOID)
#   censuscovid$GEOID <-ifelse(censuscovid$state == " Colorado",paste("0",censuscovid$GEOID,sep =""),censuscovid$GEOID)
#   censuscovid$GEOID <-ifelse(censuscovid$state == " Connecticut",paste("0",censuscovid$GEOID,sep =""),censuscovid$GEOID)
#   censuscovid$GEOID <-ifelse(censuscovid$state == " Alaska",paste("0",censuscovid$GEOID,sep =""),censuscovid$GEOID)
# # #  
# # #give timeslider data
#   df.polygon4z@data <- censuscovid

#install.packages("TSstudio",lib = "C:/R/R-4.0.2/library")
library(TSstudio)
#  
final_covid <- read.csv("final_covid.csv");final_covid <- final_covid[-c(1)]; colnames(final_covid) <- c("county","GEOID","state","date","lat","lon","confirmed","deaths")
final_covid$GEOID <-ifelse(final_covid$state == "Alabama",paste("0",final_covid$GEOID,sep =""),final_covid$GEOID)
final_covid$GEOID <-ifelse(final_covid$state == "Arkansas",paste("0",final_covid$GEOID,sep =""),final_covid$GEOID)
final_covid$GEOID <-ifelse(final_covid$state == "California",paste("0",final_covid$GEOID,sep =""),final_covid$GEOID)
final_covid$GEOID <-ifelse(final_covid$state == "Arizona",paste("0",final_covid$GEOID,sep =""),final_covid$GEOID)
final_covid$GEOID <-ifelse(final_covid$state == "Colorado",paste("0",final_covid$GEOID,sep =""),final_covid$GEOID)
final_covid$GEOID <-ifelse(final_covid$state == "Connecticut",paste("0",final_covid$GEOID,sep =""),final_covid$GEOID)
final_covid$GEOID <-ifelse(final_covid$state == "Alaska",paste("0",final_covid$GEOID,sep =""),final_covid$GEOID)

mobility2 <- read.csv("mobility2.csv"); mobility2 <- mobility2[-c(1)]
mobility2$GEOID <-ifelse(mobility2$state == "Alabama",paste("0",mobility2$GEOID,sep =""),mobility2$GEOID)
mobility2$GEOID <-ifelse(mobility2$state == "Arkansas",paste("0",mobility2$GEOID,sep =""),mobility2$GEOID)
mobility2$GEOID <-ifelse(mobility2$state == "California",paste("0",mobility2$GEOID,sep =""),mobility2$GEOID)
mobility2$GEOID <-ifelse(mobility2$state == "Arizona",paste("0",mobility2$GEOID,sep =""),mobility2$GEOID)
mobility2$GEOID <-ifelse(mobility2$state == "Colorado",paste("0",mobility2$GEOID,sep =""),mobility2$GEOID)
mobility2$GEOID <-ifelse(mobility2$state == "Connecticut",paste("0",mobility2$GEOID,sep =""),mobility2$GEOID)
mobility2$GEOID <-ifelse(mobility2$state == "Alaska",paste("0",mobility2$GEOID,sep =""),mobility2$GEOID)


```

Customer Information
===

Column {data-width=200 .sidebar}
-----------------------------------------------------------------------

```{r}
selectInput("VariableInput", label = h3("Variable"),choices = c("VulIndex","z_Over64","PopulationToGrowthRateRatio"))

# selected Var
  selectedVar <- reactive({switch(input$VariableInput, 
                                  "VulIndex"=df.polygon5$VulIndex, 
                                  "z_Over64"=df.polygon5$z_Over64, 
                                  "PopulationToGrowthRateRatio"=df.polygon5$PopulationToGrowthRateRatio)})
```

Column {data-width=450}
-----------------------------------------------------------------------

### Deomographic information by county

```{r}
 pal2 <- colorNumeric(palette = "Reds", domain=NULL)
  
  output$map <- renderLeaflet({
    
    leaflet(df.polygon5) %>% 
      addProviderTiles(providers$Stamen.TonerLite) %>% 
      setView(lng = -98.583, lat = 39.833, zoom = 4) %>%
      addPolygons(data = df.polygon5 ,
                  layerId = ~GEOID, # NEED GEOID TO BE IN THE LAYER IF YOU WANT TO CLICK AND HAVE REACTIVE PLOT
                  fillColor = ~pal2(selectedVar()),
                  popup = paste0("<strong>County: </strong>",df.polygon5$county,"<br>","<strong>Vulindex: </strong>",round(df.polygon5$z_Over64,digits=2),"<br>","<strong>Vulindex: </strong>",round(df.polygon5$PopulationToGrowthRateRatio,digits = 2)),
                  color = "#BDBDC3",
                  fillOpacity = 0.8,
                  weight = 1)%>%
      addLegend(position = "topright", pal = pal2, values = df.polygon5[[input$VariableInput]] ,
                title =  ~paste(input$VariableInput))
    
  })
  
  
  observeEvent(input$map_shape_click, { # update the location selectInput on map clicks
    p <- input$map_shape_click
    z <- input$map_shape_click$id
    print(p)
  })
  
  county_click <- eventReactive(input$map_shape_click, {
    x <- input$map_shape_click
    y <- x$id
    return(y)
    print(y)
  })
  
  county_data <- eventReactive(input$map_shape_click, {
    x <- input$map_shape_click
    z <- compare[compare$GEOID == x$id,]
    return(z)
  })
  
 
  
  leafletOutput(outputId = 'map', height = 800)
  
```

### Zipcode level map
```{r}

output$map2 <- renderLeaflet({
    z <- filter(zipmap,COUNTY == county_click())
    mapview(z,zcol = "B01003_001E")@map
  })

mapview:::mapviewOutput("map2")


```

Column {data-width=350}
-----------------------------------------------------------------------

### Population by age

```{r}

  output$plot2 <- renderPlotly({

     # PYRIMID PLOT POPULATION FOR EACH AGE GROUP
     population_by_age <- plot_ly(county_data(),x = county_data()$value, y = county_data()$AGEGROUP, color  = county_data()$SEX, type = 'bar', orientation = 'h',
                                  hoverinfo = 'y+text+name', text = county_data()$value) %>%
       layout(title = paste("Population"),bargap = 0.1, barmode = 'overlay',
              xaxis = list(tickmode = 'array', tickvals = c(min(county_data()$value), min(county_data()$value)*.75 ,min(county_data()$value)*.50,min(county_data()$value)*.25, 0,max(county_data()$value)*.25,max(county_data()$value)*.50,max(county_data()$value)*.75, max(county_data()$value)), ticktext = c(min(county_data()$value), min(county_data()$value)*.75 ,min(county_data()$value)*.50,min(county_data()$value)*.25, 0,max(county_data()$value)*.25,max(county_data()$value)*.50,max(county_data()$value)*.75, max(county_data()$value))))
     
     
   })
 plotlyOutput("plot2")

 

```

### Population by race

```{r}

  output$plot3 <- renderPlotly({

     # PYRIMID PLOT POPULATION FOR EACH AGE GROUP
     population_by_race <- plot_ly(county_data(),x = county_data()$value, y = county_data()$RACE, color  = county_data()$SEX, type = 'bar', orientation = 'h',
        hoverinfo = 'y+text+name', text = county_data()$value) %>%
  layout(bargap = 0.1, barmode = 'overlay', 
          xaxis = list(tickmode = 'array', tickvals = c(min(county_data()$value), min(county_data()$value)*.75 ,min(county_data()$value)*.50,min(county_data()$value)*.25, 0,max(county_data()$value)*.25,max(county_data()$value)*.50,max(county_data()$value)*.75, max(county_data()$value)), ticktext = c(min(county_data()$value), min(county_data()$value)*.75 ,min(county_data()$value)*.50,min(county_data()$value)*.25, 0,max(county_data()$value)*.25,max(county_data()$value)*.50,max(county_data()$value)*.75, max(county_data()$value))))
     
   })
 plotlyOutput("plot3")

 

```


Demographic Information
===============

Column {data-width=200 .sidebar}
-----------------------------------------------------------------------

```{r}
selectInput("VariableInput", label = h3("Variable"),choices = c("VulIndex","z_Over64","PopulationToGrowthRateRatio"))

# selected Var
  selectedVar <- reactive({switch(input$VariableInput, 
                                  "VulIndex"=df.polygon5$VulIndex, 
                                  "z_Over64"=df.polygon5$z_Over64, 
                                  "PopulationToGrowthRateRatio"=df.polygon5$PopulationToGrowthRateRatio)})

```

Column {data-width=450}
------------------------------------------------------------------------

### New map 

```{r}
 pal2 <- colorNumeric(palette = "Reds", domain=NULL)
  
  output$map4 <- renderLeaflet({
    
    leaflet(df.polygon5) %>% 
      addProviderTiles(providers$Stamen.TonerLite) %>% 
      setView(lng = -98.583, lat = 39.833, zoom = 4) %>%
      addPolygons(data = df.polygon5 ,
                  layerId = ~GEOID, # NEED GEOID TO BE IN THE LAYER IF YOU WANT TO CLICK AND HAVE REACTIVE PLOT
                  fillColor = ~pal2(selectedVar()),
                  popup = paste0("<strong>County: </strong>",df.polygon5$county,"<br>","<strong>Vulindex: </strong>",round(df.polygon5$z_Over64,digits=2),"<br>","<strong>Vulindex: </strong>",round(df.polygon5$PopulationToGrowthRateRatio,digits = 2)),
                  color = "#BDBDC3",
                  fillOpacity = 0.8,
                  weight = 1)%>%
      addLegend(position = "topright", pal = pal2, values = df.polygon5[[input$VariableInput]] ,
                title =  ~paste(input$VariableInput))
    
  })
  
  
  observeEvent(input$map4_shape_click, { # update the location selectInput on map clicks
    p <- input$map4_shape_click
    z <- input$map4_shape_click$id
    print(p)
  })
  
  # county_click <- eventReactive(input$map4_shape_click, {
  #   x <- input$map4_shape_click
  #   y <- x$id
  #   return(y)
  #   print(y)
  # })
  # 
  # county_data <- eventReactive(input$map4_shape_click, {
  #   x <- input$map4_shape_click
  #   z <- compare[compare$GEOID == x$id,]
  #   return(z)
  # })
  
  covid2_data <- eventReactive(input$map4_shape_click, {
    x <- input$map4_shape_click
    z <- final_covid[final_covid$GEOID == x$id,]
    final_mobility_harrison <- z
    final_mobility_harrison2 <- final_mobility_harrison[c(4,7)]
    final_mobility_harrison2$date <- as.character(final_mobility_harrison2$date)
    final_mobility_harrison2$date <- as.POSIXct(final_mobility_harrison2$date, format="%Y-%m-%d")
    final_mobility_harrison2 <- final_mobility_harrison2[order(final_mobility_harrison2$date),]
    return(final_mobility_harrison2)
  })
 
  mobility2_data <- eventReactive(input$map4_shape_click, {
    xf <- input$map4_shape_click
    zf <- mobility2[mobility2$GEOID == xf$id,]
    final_mobility_harrisonz <- zf
    final_mobility_harrison2z <- final_mobility_harrisonz[c(9,14)]
    final_mobility_harrison2z$date <- as.character(final_mobility_harrison2z$date)
    final_mobility_harrison2z$date <- as.POSIXct(final_mobility_harrison2z$date, format="%Y-%m-%d")
    final_mobility_harrison2z <- final_mobility_harrison2z[order(final_mobility_harrison2z$date),]
    return(final_mobility_harrison2z)
  })
 
  leafletOutput(outputId = 'map4', height = 800)
  

```

Column {data-width=350}
-----------------------------------------------------------------------

### covid plot

```{r}

# final_mobility_harrison <- mobility2_data()
# final_mobility_harrison2 <- final_mobility_harrison[c(4,7)]
# final_mobility_harrison2$date <- as.character(final_mobility_harrison2$date)
# final_mobility_harrison2$date <- as.POSIXct(final_mobility_harrison2$date, format="%Y-%m-%d")
# final_mobility_harrison2 <- final_mobility_harrison2[order(final_mobility_harrison2$date),]

  
 output$plot3z <- renderPlotly({
   
hildalgo_covid <-  ts_plot(covid2_data(),
         title = "County Covid Mobility",
         Xtitle = "Time",
         Ytitle = "Percent decrease",
         slider = TRUE)


})
 plotlyOutput("plot3z")
```


### covid plot

```{r}

# final_mobility_harrison <- mobility2_data()
# final_mobility_harrison2 <- final_mobility_harrison[c(4,7)]
# final_mobility_harrison2$date <- as.character(final_mobility_harrison2$date)
# final_mobility_harrison2$date <- as.POSIXct(final_mobility_harrison2$date, format="%Y-%m-%d")
# final_mobility_harrison2 <- final_mobility_harrison2[order(final_mobility_harrison2$date),]

  
 output$plot4z <- renderPlotly({
   
hildalgo_mobilityz <-  ts_plot(mobility2_data(),
         title = "County Covid Mobility",
         Xtitle = "Time",
         Ytitle = "Percent decrease",
         slider = TRUE)


})
 plotlyOutput("plot4z")
```
