---
title: "Customer Intelligence"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r global, include=FALSE}
 setwd("C:/Users/blake/OneDrive/Stryker Project/Country Leaflet Information Dashboard/Building Leaflet Final Interactive Map/Leaflet Map App")
if(!require(flexdashboard)) install.packages("flexdashboard",repos = "http://cran.us.r-project.org")
if(!require(geojsonio)) install.packages("geojsonio",repos = "http://cran.us.r-project.org")
library(sf)
library(rgdal)
library(dplyr)
library(shiny)
library(rmapshaper)
library(purrr)
library(tidycensus)
library(tidyr)
library(mapview)
library(sp)
library(geojsonio)
#install.packages("flexdashboard")
library(flexdashboard)
library(readr)
library(leaflet)
library(DT)
library(tidyverse)
library(lubridate)
library(plotly)
library(sf)
 setwd("C:/Users/blake/OneDrive/Stryker Project/Country Leaflet Information Dashboard/Building Leaflet Final Interactive Map/Leaflet Map App")

# Load data
county <- readOGR(dsn=".", layer = "cb_2018_us_county_500k")
# # # # convert the GEOID to a character (BECAUSE TIDY CENSUS IS CHARACTER FOR SF FILE)
county@data$GEOID <-as.character(county@data$GEOID)

df.polygon <- county

# # # # # # # # County shape dataframe subset this!!!
df.polygon2  <- df.polygon# moving variable

# # # # # # # # Load dataframe
census <- read.csv("census.csv");census <- census[-c(1)];census <- census[c(1,2,3,7,10,14)];census$GEOID <-  as.character(census$GEOID)
# #  #  # 

census$GEOID <-ifelse(census$state == " Alabama",paste("0",census$GEOID,sep =""),census$GEOID)
census$GEOID <-ifelse(census$state == " Arkansas",paste("0",census$GEOID,sep =""),census$GEOID)
census$GEOID <-ifelse(census$state == " California",paste("0",census$GEOID,sep =""),census$GEOID)
census$GEOID <-ifelse(census$state == " Arizona",paste("0",census$GEOID,sep =""),census$GEOID)
census$GEOID <-ifelse(census$state == " Colorado",paste("0",census$GEOID,sep =""),census$GEOID)
census$GEOID <-ifelse(census$state == " Connecticut",paste("0",census$GEOID,sep =""),census$GEOID)
census$GEOID <-ifelse(census$state == " Alaska",paste("0",census$GEOID,sep =""),census$GEOID)

df.polygon5 <- rmapshaper::ms_simplify(df.polygon2, keep = 0.05, keep_shapes = TRUE)

df.polygon5@data <- left_join(df.polygon5@data, census,by = c("GEOID"),all.x = TRUE)

compare <- read.csv("compare.csv");compare <- compare[-c(1)]
compare$GEOID <-ifelse(grepl("Alabama", compare$NAME, fixed = TRUE),paste("0",compare$GEOID,sep =""),compare$GEOID)
 compare$GEOID <-ifelse(grepl("Arkansas", compare$NAME, fixed = TRUE),paste("0",compare$GEOID,sep =""),compare$GEOID)
 compare$GEOID <-ifelse(grepl("California", compare$NAME, fixed = TRUE),paste("0",compare$GEOID,sep =""),compare$GEOID)
 compare$GEOID <-ifelse(grepl("Arizona", compare$NAME, fixed = TRUE),paste("0",compare$GEOID,sep =""),compare$GEOID)
 compare$GEOID <-ifelse(grepl("Colorado", compare$NAME, fixed = TRUE),paste("0",compare$GEOID,sep =""),compare$GEOID)
 compare$GEOID <-ifelse(grepl("Connecticut", compare$NAME, fixed = TRUE),paste("0",compare$GEOID,sep =""),compare$GEOID)
 compare$GEOID <-ifelse(grepl("Alaska", compare$NAME, fixed = TRUE),paste("0",compare$GEOID,sep =""),compare$GEOID)
 


```

Column {data-width=200 .sidebar}
-----------------------------------------------------------------------

```{r}
selectInput("VariableInput", label = h3("Variable"),choices = c("VulIndex","z_Over64","PopulationToGrowthRateRatio"))

# selected Var
  selectedVar <- reactive({switch(input$VariableInput, 
                                  "VulIndex"=df.polygon5$VulIndex, 
                                  "z_Over64"=df.polygon5$z_Over64, 
                                  "PopulationToGrowthRateRatio"=df.polygon5$PopulationToGrowthRateRatio)})
```

Column {data-width=450}
-----------------------------------------------------------------------

### Deomographic information by county

```{r}
 pal2 <- colorNumeric(palette = "Reds", domain=NULL)
  
  output$map <- renderLeaflet({
    
    leaflet(df.polygon5) %>% 
      addProviderTiles(providers$Stamen.TonerLite) %>% 
      setView(lng = -98.583, lat = 39.833, zoom = 4) %>%
      addPolygons(data = df.polygon5 ,
                  layerId = ~GEOID, # NEED GEOID TO BE IN THE LAYER IF YOU WANT TO CLICK AND HAVE REACTIVE PLOT
                  fillColor = ~pal2(selectedVar()),
                  popup = paste0("<strong>County: </strong>",df.polygon5$county,"<br>","<strong>Vulindex: </strong>",round(df.polygon5$z_Over64,digits=2),"<br>","<strong>Vulindex: </strong>",round(df.polygon5$PopulationToGrowthRateRatio,digits = 2)),
                  color = "#BDBDC3",
                  fillOpacity = 0.8,
                  weight = 1)%>%
      addLegend(position = "topright", pal = pal2, values = df.polygon5[[input$VariableInput]] ,
                title =  ~paste(input$VariableInput))
    
  })
  
  
  observeEvent(input$map_shape_click, { # update the location selectInput on map clicks
    p <- input$map_shape_click
    z <- input$map_shape_click$id
    print(p)
  })
  
  county_click <- eventReactive(input$map_shape_click, {
    x <- input$map_shape_click
    y <- x$id
    return(y)
    print(y)
  })
  
  county_data <- eventReactive(input$map_shape_click, {
    x <- input$map_shape_click
    z <- compare[compare$GEOID == x$id,]
    return(z)
  })
  
 
  
  leafletOutput(outputId = 'map', height = 800)
  
```

Column {data-width=350}
-----------------------------------------------------------------------

### Population by age

```{r}

  output$plot2 <- renderPlotly({

     # PYRIMID PLOT POPULATION FOR EACH AGE GROUP
     population_by_age <- plot_ly(county_data(),x = county_data()$value, y = county_data()$AGEGROUP, color  = county_data()$SEX, type = 'bar', orientation = 'h',
                                  hoverinfo = 'y+text+name', text = county_data()$value) %>%
       layout(title = paste("Population"),bargap = 0.1, barmode = 'overlay',
              xaxis = list(tickmode = 'array', tickvals = c(min(county_data()$value), min(county_data()$value)*.75 ,min(county_data()$value)*.50,min(county_data()$value)*.25, 0,max(county_data()$value)*.25,max(county_data()$value)*.50,max(county_data()$value)*.75, max(county_data()$value)), ticktext = c(min(county_data()$value), min(county_data()$value)*.75 ,min(county_data()$value)*.50,min(county_data()$value)*.25, 0,max(county_data()$value)*.25,max(county_data()$value)*.50,max(county_data()$value)*.75, max(county_data()$value))))
     
     
   })
 plotlyOutput("plot2")

 

```

### Population by race

```{r}

  output$plot3 <- renderPlotly({

     # PYRIMID PLOT POPULATION FOR EACH AGE GROUP
     population_by_race <- plot_ly(county_data(),x = county_data()$value, y = county_data()$RACE, color  = county_data()$SEX, type = 'bar', orientation = 'h',
        hoverinfo = 'y+text+name', text = county_data()$value) %>%
  layout(bargap = 0.1, barmode = 'overlay', 
          xaxis = list(tickmode = 'array', tickvals = c(min(county_data()$value), min(county_data()$value)*.75 ,min(county_data()$value)*.50,min(county_data()$value)*.25, 0,max(county_data()$value)*.25,max(county_data()$value)*.50,max(county_data()$value)*.75, max(county_data()$value)), ticktext = c(min(county_data()$value), min(county_data()$value)*.75 ,min(county_data()$value)*.50,min(county_data()$value)*.25, 0,max(county_data()$value)*.25,max(county_data()$value)*.50,max(county_data()$value)*.75, max(county_data()$value))))
     
   })
 plotlyOutput("plot3")

 

```
